# environment: "development"
environment: "production"

service:
  name: "template"
  grpc:
    host: "localhost"
    port: ":8082"
    endpoint: ":8083"
  http:
    host: "localhost"
    port: ":8081"
    endpoint: ":8080"
  debug:
    host: "localhost"
    port: ":8084"
    endpoint: ":8085"

jaeger:
  hostPort: "jaeger:6831"
  logSpans: true

redis:
  username: ""
  password: ""
  db: 0
  host: "redis:6379"
  logger: ""
  smsDuration: "500s"
  smsCodeVerification: "100s"
  userDuration: "1000000000s"

multiInstanceMode: false

log:
  disableColors: false
  quoteEmptyFields: false

etcd:
  endpoints:
    - "http://etcd:2379"
    - "http://etcd2:2379"
    - "http://etcd3:2379"
  watchList:
    - "redis"
    - "service"
    - "mysql"

mysql:
  username: "root"
  password: "password"
  host: "db"
  schema: "blogfa_auth"
  driver: "mysql"
  automigrate: true
  logger: true

Nats:
  username: ""
  password: ""
  auth: false
  endpoints:
    - "nats://nats:4222"

jwt:
  secret: "xxxxxxxxxxxxx"
  rSecret: "yyyyyyyyyyyyyyy"
